stages:
  - build
  - test

run_unit_tests:
  image: docker-registry.ebrains.eu/model-catalog/node:22-alpine
  stage: test
  rules:
    - changes:
      - apps/model_catalog/**/*
      - .gitlab-ci.yml
  script:
    - cd apps/model_catalog
    - npm ci --legacy-peer-deps
    - npm run test
  tags:
    - docker-runner

run_cypress_tests:
  image: cypress/browsers:22.19.0
  stage: test
  variables:
    VITE_SKIP_AUTH: "true"
  rules:
    - if: '$CI_COMMIT_REF_NAME == "staging"'
      changes:
        - apps/model_catalog/**/*
        - .gitlab-ci.yml
  script:
    - cd apps/model_catalog
    # install dependencies
    - npm ci --legacy-peer-deps
    # start server and run Cypress tests
    - npm run e2e:ci
  tags:
    - docker-runner

build_apps_staging_image:
  stage: build
  rules:
      - if: '$CI_COMMIT_REF_NAME == "staging"'
        changes:
          - apps/**/*
  script:
    - docker build -f apps/deployment/Dockerfile.staging -t docker-registry.ebrains.eu/model-catalog/model-catalog-v2:staging ./apps
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_SECRET docker-registry.ebrains.eu
    - docker push docker-registry.ebrains.eu/model-catalog/model-catalog-v2:staging
  tags:
    - shell-runner

build_apps_prod_image:
  stage: build
  rules:
      - if: '$CI_COMMIT_REF_NAME == "main"'
        changes:
          - apps/**/*
  script:
    - docker build -f apps/deployment/Dockerfile.prod -t docker-registry.ebrains.eu/model-catalog/model-catalog-v2:prod ./apps
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_SECRET docker-registry.ebrains.eu
    - docker push docker-registry.ebrains.eu/model-catalog/model-catalog-v2:prod
  tags:
    - shell-runner
