export function createMockDatastore(overrides = {}) {
    return {
        auth: { token: "mock-token", authenticated: true },
        baseUrl: "https://mock-api.example.com",
        models: {},
        tests: {},
        summary_results: {},
        extended_results: {},
        projects: [],
        vocab: null,
        comments: {},
        queries: { models: {}, tests: {} },
        driveToken: null,
        getRequestConfig: vi.fn(() => ({
            headers: { Authorization: "Bearer mock-token" },
        })),
        get: vi.fn().mockResolvedValue({ data: [] }),
        post: vi.fn().mockResolvedValue({ data: {} }),
        put: vi.fn().mockResolvedValue({ data: {} }),
        delete: vi.fn().mockResolvedValue({}),
        queryModels: vi.fn().mockResolvedValue([]),
        queryTests: vi.fn().mockResolvedValue([]),
        getModel: vi.fn().mockResolvedValue({}),
        getTest: vi.fn().mockResolvedValue({}),
        getResult: vi.fn().mockResolvedValue({}),
        getResultsByModel: vi.fn().mockResolvedValue([]),
        getResultsByTest: vi.fn().mockResolvedValue([]),
        getResultsByModelInstances: vi.fn().mockResolvedValue([]),
        getResultsByTestInstance: vi.fn().mockResolvedValue([]),
        getProjects: vi.fn().mockResolvedValue([]),
        getValidFilterValues: vi.fn().mockResolvedValue({}),
        createModel: vi.fn().mockResolvedValue({}),
        updateModel: vi.fn().mockResolvedValue({}),
        createModelInstance: vi.fn().mockResolvedValue({}),
        updateModelInstance: vi.fn().mockResolvedValue({}),
        createTest: vi.fn().mockResolvedValue({}),
        updateTest: vi.fn().mockResolvedValue({}),
        createTestInstance: vi.fn().mockResolvedValue({}),
        updateTestInstance: vi.fn().mockResolvedValue({}),
        modelAliasIsUnique: vi.fn().mockResolvedValue(true),
        testAliasIsUnique: vi.fn().mockResolvedValue(true),
        getModelInstanceFromVersion: vi.fn().mockResolvedValue({ data: [] }),
        getModelInstanceFromID: vi.fn().mockResolvedValue({ data: {} }),
        getTestInstanceFromVersion: vi.fn().mockResolvedValue({ data: [] }),
        getTestInstanceFromID: vi.fn().mockResolvedValue({ data: {} }),
        getComments: vi.fn().mockResolvedValue([]),
        createComment: vi.fn().mockResolvedValue({}),
        updateComment: vi.fn().mockResolvedValue({}),
        deleteComment: vi.fn().mockResolvedValue(undefined),
        getDriveToken: vi.fn().mockResolvedValue("mock-drive-token"),
        ...overrides,
    };
}
